# Generated by Django 2.0.2 on 2018-02-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=models.IntegerField(blank=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.IntegerField(blank=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rg',
            field=models.IntegerField(blank=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.IntegerField(blank=True, verbose_name='Telefone'),
        ),
    ]
