# Generated by Django 2.0.2 on 2018-02-02 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(max_length=1000, verbose_name='Objeto')),
                ('numero', models.IntegerField(verbose_name='Número do ítem')),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Valor Unitário')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade do Item')),
                ('unidade', models.CharField(max_length=100, verbose_name='Unidade')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDoPregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Preço Inicial')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Valor do Lance')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedores.Fornecedor')),
                ('itemDoPregao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ItemDoPregao')),
            ],
        ),
        migrations.CreateModel(
            name='Pregao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=20, verbose_name='Modalidade')),
                ('numero', models.CharField(max_length=100, verbose_name='Nº do Pregão')),
                ('numeroProcesso', models.CharField(max_length=100, verbose_name='Nº do Processo')),
                ('objeto', models.CharField(max_length=1000, verbose_name='Objeto')),
                ('valorEstimado', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Valor Estimado')),
                ('pregoeiro', models.CharField(max_length=100, verbose_name='Pregoeiro')),
                ('equipeDeApoio', models.CharField(max_length=300, verbose_name='Equipe de Apoio')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Valor da Proposta')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedores.Fornecedor')),
                ('itemDoPregao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ItemDoPregao')),
            ],
        ),
        migrations.AddField(
            model_name='itemdopregao',
            name='pregao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pregao'),
        ),
    ]
